// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: internal/grpc/proto/notification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationStatus int32

const (
	NotificationStatus_UNKNOWN   NotificationStatus = 0
	NotificationStatus_QUEUED    NotificationStatus = 1
	NotificationStatus_DELIVERED NotificationStatus = 2
	NotificationStatus_FAILED    NotificationStatus = 3
	NotificationStatus_RETRYING  NotificationStatus = 4
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "QUEUED",
		2: "DELIVERED",
		3: "FAILED",
		4: "RETRYING",
	}
	NotificationStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"QUEUED":    1,
		"DELIVERED": 2,
		"FAILED":    3,
		"RETRYING":  4,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_notification_proto_enumTypes[0]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_notification_proto_rawDescGZIP(), []int{0}
}

// Post represents a user's new post
type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_internal_grpc_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type NotificationResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PostId              string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	NotificationsQueued int32                  `protobuf:"varint,2,opt,name=notifications_queued,json=notificationsQueued,proto3" json:"notifications_queued,omitempty"`
	Success             bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_internal_grpc_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationResponse) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *NotificationResponse) GetNotificationsQueued() int32 {
	if x != nil {
		return x.NotificationsQueued
	}
	return 0
}

func (x *NotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // User receiving the notification
	PostId        string                 `protobuf:"bytes,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`                         // Related post ID
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`                   // User who created the post
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                     // Notification content
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`               // When the notification was created
	Read          bool                   `protobuf:"varint,7,opt,name=read,proto3" json:"read,omitempty"`                                          // Whether notification has been read
	Status        NotificationStatus     `protobuf:"varint,8,opt,name=status,proto3,enum=notification.NotificationStatus" json:"status,omitempty"` // Current status of the notification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_internal_grpc_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_notification_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Notification) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Notification) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *Notification) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_UNKNOWN
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FollowerIds   []string               `protobuf:"bytes,3,rep,name=follower_ids,json=followerIds,proto3" json:"follower_ids,omitempty"`
	FollowingIds  []string               `protobuf:"bytes,4,rep,name=following_ids,json=followingIds,proto3" json:"following_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_grpc_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFollowerIds() []string {
	if x != nil {
		return x.FollowerIds
	}
	return nil
}

func (x *User) GetFollowingIds() []string {
	if x != nil {
		return x.FollowingIds
	}
	return nil
}

var File_internal_grpc_proto_notification_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_notification_proto_rawDesc = "" +
	"\n" +
	"&internal/grpc/proto/notification.proto\x12\fnotification\"l\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"|\n" +
	"\x14NotificationResponse\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x121\n" +
	"\x14notifications_queued\x18\x02 \x01(\x05R\x13notificationsQueued\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\xf4\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\tR\x06postId\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x12\n" +
	"\x04read\x18\a \x01(\bR\x04read\x128\n" +
	"\x06status\x18\b \x01(\x0e2 .notification.NotificationStatusR\x06status\"z\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\ffollower_ids\x18\x03 \x03(\tR\vfollowerIds\x12#\n" +
	"\rfollowing_ids\x18\x04 \x03(\tR\ffollowingIds*V\n" +
	"\x12NotificationStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x01\x12\r\n" +
	"\tDELIVERED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\f\n" +
	"\bRETRYING\x10\x042^\n" +
	"\x13NotificationService\x12G\n" +
	"\vPublishPost\x12\x12.notification.Post\x1a\".notification.NotificationResponse\"\x00BSZQgithub.com/suyashXD/Distributed-Notification-Delivery-Service/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_notification_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_notification_proto_rawDescData []byte
)

func file_internal_grpc_proto_notification_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_notification_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_notification_proto_rawDesc), len(file_internal_grpc_proto_notification_proto_rawDesc)))
	})
	return file_internal_grpc_proto_notification_proto_rawDescData
}

var file_internal_grpc_proto_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_grpc_proto_notification_proto_goTypes = []any{
	(NotificationStatus)(0),      // 0: notification.NotificationStatus
	(*Post)(nil),                 // 1: notification.Post
	(*NotificationResponse)(nil), // 2: notification.NotificationResponse
	(*Notification)(nil),         // 3: notification.Notification
	(*User)(nil),                 // 4: notification.User
}
var file_internal_grpc_proto_notification_proto_depIdxs = []int32{
	0, // 0: notification.Notification.status:type_name -> notification.NotificationStatus
	1, // 1: notification.NotificationService.PublishPost:input_type -> notification.Post
	2, // 2: notification.NotificationService.PublishPost:output_type -> notification.NotificationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_notification_proto_init() }
func file_internal_grpc_proto_notification_proto_init() {
	if File_internal_grpc_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_notification_proto_rawDesc), len(file_internal_grpc_proto_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_notification_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_notification_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_notification_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_notification_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_notification_proto = out.File
	file_internal_grpc_proto_notification_proto_goTypes = nil
	file_internal_grpc_proto_notification_proto_depIdxs = nil
}
